apiVersion: apps/v1
kind: Deployment
metadata:
  name: atividade
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atividade
  template:
    metadata:
      labels:
        app: atividade
    spec:
      containers:
        - name: atividade
          image: atividade:latest
          imagePullPolicy: Never 
          ports:
          - containerPort: 3000
