apiVersion: apps/v1
kind: Deployment
metadata:
  name: atividade
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atividade
  template:
    metadata:
      labels:
        app: atividade
    spec:
      containers:
        - name: atividade
          # ---- ALTERAÇÕES AQUI ----
          image: 3riccolpo/atividade:latest  
          imagePullPolicy: IfNotPresent     # Pode ser 'Always'
          # -------------------------
          ports:
          - containerPort: 3000